package Bitwise;
//https://leetcode.com/problems/find-the-difference/
//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.
public class findDifference {
    public static void main(String[] args) {
        String s="";
        String t="y";
        System.out.println(findTheDifference(s,t));
    }
    public static char findTheDifference(String s, String t) {
        String total= s+t;
        int ans=0;
        for (int i=0; i<total.length();i++){
            ans^=total.charAt(i);
        }
        return (char) ans;
    }
}
